print("=" * 50)
print("WELCOME TO PROJECT NOVA")
print("=" * 50)
print()
print("Version : v0.0.1")
print("Status  : Under Development")
print()
print("Today's Feature")
print("- Welcome Screen")
print()
print("Made by Adeeb")
print("=" * 50)